columns:
  START:
    normalised_colname: start_time
    type: datetimestamp
    description: The date and time when the medication began.
  STOP:
    normalised_colname: stop_time
    type: datetimestamp
    description: The date and time when the medication ended.
  PATIENT:
    normalised_colname: patient_id
    type: str
    description: Unique identifier for the specific patient and encounterid links to this patient_id
  PAYER:
    normalised_colname: payer_id
    type: str
    description: Unique identifier for the payer, might be insurance
  ENCOUNTER:
    normalised_colname: encounter_id
    type: str
    description: Encounter id during which the medication was prescribed
  CODE:
    normalised_colname: code
    type: str
    description: Probably the code representing the medication
  DESCRIPTION:
    normalised_colname: medicine_description
    type: str
    description: A description of the medication, including dosage and form
  BASE_COST:
    normalised_colname: base_cost
    type: float
    description: The base cost of a single unit or dose of the medication
  PAYER_COVERAGE:
    normalised_colname: payer_coverage
    type: float
    description: amount covered by payer may be insurance
  DISPENSES:
    normalised_colname: medicine_dispenses
    type: float
    description: Probably, the number of times the medication was dispensed to the patient 
  TOTALCOST:
    normalised_colname: total_cost_of_medicine
    type: float
    description: total cost of the medications
  REASONCODE:
    normalised_colname: reason_code_for_medication
    type: str
    description: May be diagnosis code due to which medication was presribed I assume
  REASONDESCRIPTION:
    normalised_colname: reason_description_for_medication
    type: str
    description: Description of reason code

  
